### ISSUE TITLE
为什么会出现移动端 1px 问题？如何解决？

### ISSUE THREAD

**Issue by xianshannan** [xianshannan/interview#38]
## 为什么会出现移动端 1px 问题？

那么为什么会产生这个问题呢？主要是跟一个东西有关，DPR(devicePixelRatio)  设备像素比，它是默认缩放为100%的情况下，设备像素和CSS像素的比值。

```js
window.devicePixelRatio = 物理像素 / CSS像素
// 设备像素比 ＝ 物理像素 / 设备独立像素
```

目因为 retina 屏的分辨率始终是普通屏幕的 2 倍，1px 的边框在 `devicePixelRatio=2` 的 retina 屏下会显示成 2px，所以在高清瓶下看着 1px 总是感觉变粗了。

## 解决方案

解决方案有许多的，这里就列举写比较通用和常用的处理方式。

### 使用 transfrom: scale(.5) 进行缩放

这个是比较通用的方式，而且相对简单。

```css
.1px-t {
  position: relative;
}
.1px-t:before {
  content: " ";
  position: absolute;
  left: 0;
  right: 0;
  height: 1px;
  color: #f1f1f1;
}
```

全机型兼容，实现了真正的1px，而且可以圆角。

### 设置 viewport 的 scale 值

这个解决方案是利用 viewport+rem+js 实现的，可以参考了网上的一个例子 [移动端1像素边框问题的解决方案](https://link.juejin.im/?target=https%3A%2F%2Fblog.csdn.net%2Fbbnbf%2Farticle%2Fdetails%2F51580569)，但是实际应用并没有那么简单。

全机型兼容，可以直接写`1px`，但是只适用于新的项目，老项目可能改动大，处理成本相对大。
