### ISSUE TITLE
介绍一下标准的CSS的盒子模型？与低版本IE的盒子模型有什么不同的？

### ISSUE THREAD

**Issue by xianshannan** [xianshannan/interview#41]
盒子模型就是元素在网页中的实际占位，**有两种：**

- 标准盒子模型和IE盒子模型标准(W3C)盒子模型

  内容（content）+ 填充（padding）+ 边框（border）+ 边界（margin）

  宽高指的是 content 的宽高

- 低版本IE盒子模型

  内容（content + padding + border）+ 边界 margin

  宽高指的是 `content + padding + border ` 部分的宽高

###  CSS 如何设置这两种模型？

```less
box-sizing: content-box; // 这是默认值，W3C 盒子模型
box-sizing: border-box;// IE 盒子模型
```

从布局角度来看，个人认为设置为 `border-box` 会相对友好点，所以一般这样设置：

```less
*, *::before, *::after, *:before, *:after {
  box-sizing: border-box;
}
```

确保所有的原生初始的 box-sizing 为 border-box。
