### ISSUE TITLE
说说你对 box-sizing 属性的了解

### ISSUE THREAD

**Issue by xianshannan** [xianshannan/interview#46]
box-sizing 有两种盒子模式，用来控制浏览器的盒子模型，默认值为 `content-box`。

由于浏览器刚问世的时候，不同浏览器商，有些标准是不一致的，所以就导致出现了两种代办的盒子模型。

-  **W3C的标准盒子模型** （content-box）

  内容（content）+ 填充（padding）+ 边框（border）+ 边界（margin）

  宽高指的是 content 的宽高

-  **IE 盒子模型** （border-box）

  内容（content + padding + border）+ 边界 margin

  宽高指的是 `content + padding + border` 部分的宽高

从布局角度来看，个人认为设置为 `border-box` 会相对友好点，所以一般这样设置：

```less
*, *::before, *::after, *:before, *:after {
  box-sizing: border-box;
}
```

确保所有的原生初始的 box-sizing 为 border-box。
