### ISSUE TITLE
CSS 选择器有哪些？

### ISSUE THREAD

**Issue by xianshannan** [xianshannan/interview#48]
可能网上的总结大同小异，但是这里还是把 CSS 选择器总结为四大类：

- 基本选择器
- 属性选择器
- 伪类选择器
- 伪元素选择器

这里列举这种分类，但是不会做详细用法说明。

### 基本选择器

基本选择器包括

- 通配符选择器 `*`

  可以设置所有的元素，一般用作初始化设置，即所谓的 reset.css 的作用。

  ```css
  * {
    padding: 0;
    margin: 0;
  }
  ```

-  id 选择器

  ```css
  #container {
    background: #ccc;
  }
  ```

-  类选择器（.className） 

  ```css
  .container {
    background: #ccc;
  }
  ```

-  标签(元素)选择器

  ```css
  p {
    line-height: 20px;
  }
  ```

-  后代选择器

  只要是后代的元素都会生效。

  ```css
  ul li {
    list-style: unset;
  }
  ```

-  子选择器

  li 是 ul 子元素，属于父子关系，爷孙关系和更深层的后代关系不生效。

  ```css
  ul > li {
    list-style: unset;
  }
  ```

- 相邻兄弟选择器

  ```html
  <div class="one"></div>
  <div class="two">这里生效</div>
  <div class="two">这里不生效</div>
  <style>
    .one + .two {
      color: red;
    }
  </style>
  ```

- 通用兄弟选择器

  可以对比上面的**相邻兄弟选择器**。

  ```html
  <div class="one"></div>
  <div class="two">这里生效</div>
  <div class="two">这里生效</div>
  <div>
    <div class="two">这里不生效</div>
  </div>
  <style>
    .one ~ .two {
      color: red;
    }
  </style>
  ```

### 属性选择器

属性选择器不会分这么多类型，这里其实就只有一种类型。

| 选择器                  | 描述                                                         |
| ----------------------- | ------------------------------------------------------------ |
| [*attribute*]           | 用于选取带有指定属性的元素。                                 |
| [*attribute*=*value*\]  | 用于选取带有指定属性和值的元素。                             |
| [*attribute*~=*value*]  | 用于选取属性值中包含指定词汇的元素。                         |
| [*attribute*\|=*value*] | 用于选取带有以指定值开头的属性值的元素，该值必须是整个单词。 |
| [*attribute*^=*value*]  | 匹配属性值以指定值开头的每个元素。                           |
| [*attribute*$=*value*]  | 匹配属性值以指定值结尾的每个元素。                           |
| [*attribute*\*=*value*] | 匹配属性值中包含指定值的每个元素。                           |

用法例子如下

```css
[title] {}
div[title] {}
.className[title] {}
.idName[title] {}
```

### 伪类选择器

伪类选择器实在太多，这里就不一一列举。

伪类一般格式如下：

```CSS
selector:pseudo-class {
  property: value;
}
```

一些实例如下：

```css
a:link {color: #FF0000}		/* 未访问的链接 */
a:visited {color: #00FF00}	/* 已访问的链接 */
a:hover {color: #FF00FF}	/* 鼠标移动到链接上 */
a:active {color: #0000FF}	/* 选定的链接 */
a:first-child {color: #0000FF}	/* 选定第一个元素 */
```

### 伪元素选择器

在 CSS2 中，伪元素跟伪类长得一样的，下面只有这几个是伪元素：

只要相当于新增一个元素的，就属于伪元素，我们常用的就是 `:before` 和 `:after` 了。

| 属性          | 描述                             | CSS  |
| :------------ | :------------------------------- | :--- |
| :first-letter | 向文本的第一个字母添加特殊样式。 | 1    |
| :first-line   | 向文本的首行添加特殊样式。       | 1    |
| :before       | 在元素之前添加内容。             | 2    |
| :after        | 在元素之后添加内容。             | 2    |

CSS3 中为了区别伪类，伪元素进行了一点的调整（当然还兼容之前的用法），在以前的基础上增加了一个 `:`，如下：

```css
::first-letter
::first-line
::before
::after
```
